<!-- Modal -->
<div class="modal fade" id="file-modal-<?php echo $this->index ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <img class="img-fluid" src="<?php echo $this->img_src; ?>" alt="">
      </div>
    </div>
  </div>
</div>
